"""localnetwork table

Revision ID: f168db24f1fd
Revises: d9900be22270
Create Date: 2020-05-01 07:13:18.946331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f168db24f1fd'
down_revision = 'd9900be22270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pc_name', sa.String(length=64), nullable=True),
    sa.Column('ip_addr', sa.String(length=64), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_addr')
    )
    op.create_index(op.f('ix_local_network_pc_name'), 'local_network', ['pc_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_local_network_pc_name'), table_name='local_network')
    op.drop_table('local_network')
    # ### end Alembic commands ###
